# This workflow disables the default GitHub Pages deployment
# to prevent conflicts with our custom pkgdown deployment
name: Disable GitHub Pages Auto-Deploy

on:
  # This workflow never runs automatically
  workflow_dispatch:

jobs:
  disable-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Disable GitHub Pages Auto-Deploy
        run: |
          echo "This workflow serves as a placeholder to prevent GitHub's automatic pages-build-deployment"
          echo "The actual documentation deployment is handled by pkgdown.yaml workflow"
